### ISSUE TITLE
doc: publishing to nuget

### ISSUE THREAD

**Issue by justinmk** [neovim/nvim.net#3]
@b-r-o-c-k What are the steps you follow to publish to nuget?

**Comment by b-r-o-c-k** [comment]
I set up automatic publishing for all commits on the master branch. The NuGet Gallery API key inside the appveyor.yml just needs to be updated to make it work.

**Comment by justinmk** [comment]
Resolved by https://github.com/neovim/nvim.net/commit/bc8e3a2a98ad5a9fd3fb0eaa55730d0d9b078dfc thanks to @b-r-o-c-k 's instructions.

> Alternatively, you could publish the package on the NuGet Gallery using your own account or create one for the Neovim organization: 
> https://blog.nuget.org/20180417/organizations-on-nuget-org.html
