### ISSUE TITLE
API generator: NvimAPI already contains a definition for 'Put'

### ISSUE THREAD

**Issue by justinmk** [neovim/nvim.net#5]
Seems like the API generator might be confused about the new `nvim_put` API function?

https://travis-ci.org/neovim/nvim.net/builds/584789660

```
NvimAPI.generated.cs(459,17): error CS0102: The type 'NvimAPI' already contains a definition for 'Put' [/home/travis/build/neovim/nvim.net/src/NvimClient.API/NvimClient.API.csproj]
```

**Comment by b-r-o-c-k** [comment]
This is caused by the `put` function having the same name as the `put` UI event.  One possible solution is to  move all the UI events into a separate class, so they can't conflict with any function names. 
(e.g. `nvim.Put += ...` would become `nvim.UI.Put += ...`)

**Comment by justinmk** [comment]
> (e.g. `nvim.Put += ...` would become `nvim.UI.Put += ...`)

👍  or maybe suffix all events with `Event` ? This is similar to the convention for new Nvim events going forward: all events are named `nvim_*_event` (ignoring the fact that the legacy `redraw` event is where all the "UI events" go, for historical reasons...)
